-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 12:09:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_peliculas_puebla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_peliculas_puebla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_peliculas_puebla` DEFAULT CHARACTER SET utf8 ;
USE `db_peliculas_puebla` ;

-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblcategoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tbldirector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tbldirector` (
  `id_director` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `ap_paterno` VARCHAR(50) NOT NULL,
  `ap_materno` VARCHAR(50) NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id_director`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblpelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblpelicula` (
  `id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  `sinopsis` VARCHAR(200) NOT NULL,
  `imagen_pelicula` BLOB NOT NULL,
  `year_lanzamiento` INT NOT NULL,
  `clasificacion` VARCHAR(20) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_director` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`),
  INDEX `fk_tblpelicula_tblcategoria_idx` (`id_categoria` ASC) INVISIBLE,
  INDEX `fk_tblpelicula_tbldirector1_idx` (`id_director` ASC) VISIBLE,
  CONSTRAINT `fk_tblpelicula_tblcategoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_peliculas_puebla`.`tblcategoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblpelicula_tbldirector1`
    FOREIGN KEY (`id_director`)
    REFERENCES `db_peliculas_puebla`.`tbldirector` (`id_director`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblactor` (
  `id_actor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `ap_paterno` VARCHAR(50) NOT NULL,
  `ap_materno` VARCHAR(50) NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id_actor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblpelicula_tblactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblpelicula_tblactor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pelicula` INT NOT NULL,
  `id_actor` INT NOT NULL,
  INDEX `fk_tblpelicula_has_tblactor_tblactor1_idx` (`id_actor` ASC) VISIBLE,
  INDEX `fk_tblpelicula_has_tblactor_tblpelicula1_idx` (`id_pelicula` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tblpelicula_has_tblactor_tblpelicula1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `db_peliculas_puebla`.`tblpelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblpelicula_has_tblactor_tblactor1`
    FOREIGN KEY (`id_actor`)
    REFERENCES `db_peliculas_puebla`.`tblactor` (`id_actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblrol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblusuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `tblrol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tblusuario_tblrol1_idx` (`tblrol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_tblusuario_tblrol1`
    FOREIGN KEY (`tblrol_id_rol`)
    REFERENCES `db_peliculas_puebla`.`tblrol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblestado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `abreviacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblsexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblsexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblcliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblcliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `ap_paterno` VARCHAR(50) NOT NULL,
  `ap_materno` VARCHAR(50) NOT NULL,
  `rfc` VARCHAR(50) NOT NULL,
  `curp` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `id_estado` INT NOT NULL,
  `id_sexo` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_tblcliente_tblestado1_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_tblcliente_tblsexo1_idx` (`id_sexo` ASC) VISIBLE,
  CONSTRAINT `fk_tblcliente_tblestado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `db_peliculas_puebla`.`tblestado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblcliente_tblsexo1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `db_peliculas_puebla`.`tblsexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tbladministrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tbladministrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `ap_paterno` VARCHAR(50) NOT NULL,
  `ap_materno` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_administrador`),
  INDEX `fk_tbladministrador_tblusuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbladministrador_tblusuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_peliculas_puebla`.`tblusuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblmembresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblmembresia` (
  `id_membresia` INT NOT NULL AUTO_INCREMENT,
  `membresia` VARCHAR(50) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_termino` DATE NOT NULL,
  `tblcliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_membresia`),
  INDEX `fk_tblmembresia_tblcliente1_idx` (`tblcliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tblmembresia_tblcliente1`
    FOREIGN KEY (`tblcliente_id_cliente`)
    REFERENCES `db_peliculas_puebla`.`tblcliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_peliculas_puebla`.`tblpelicula_tblcliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_peliculas_puebla`.`tblpelicula_tblcliente` (
  `id` VARCHAR(45) NOT NULL,
  `vista` INT NOT NULL,
  `tblpelicula_id_pelicula` INT NOT NULL,
  `tblcliente_id_cliente` INT NOT NULL,
  INDEX `fk_tblpelicula_has_tblcliente_tblcliente1_idx` (`tblcliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_tblpelicula_has_tblcliente_tblpelicula1_idx` (`tblpelicula_id_pelicula` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tblpelicula_has_tblcliente_tblpelicula1`
    FOREIGN KEY (`tblpelicula_id_pelicula`)
    REFERENCES `db_peliculas_puebla`.`tblpelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblpelicula_has_tblcliente_tblcliente1`
    FOREIGN KEY (`tblcliente_id_cliente`)
    REFERENCES `db_peliculas_puebla`.`tblcliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
