INSERT INTO `tblestado` (`nombre`,`abreviacion`) VALUES 
	('Aguascalientes','AS'),
	('Baja California','BC'),
	('Baja California Sur','BS'),
	('Campeche','CC'),
	('Chiapas','CS'),
	('Chihuahua','CH'),
	('Coahuila','CL'),
	('Colima','CM'),
	('Ciudad de México','DF'),
	('Durango','DG'),
	('Estado de México','MC'),
	('Guanajuato','GT'),
	('Guerrero','GR'),
	('Hidalgo','HG'),
	('Jalisco','JC'),
	('Michoacán','MN'),
	('Morelos','MS'),
	('Nayarit','NT'),
	('Nuevo León','NL'),
	('Oaxaca','OC'),
	('Puebla','PL'),
	('Querétaro','QO'),
	('Quintana Roo','QR'),
	('San Luis Potosí','SP'),
	('Sinaloa','SL'),
	('Sonora','SR'),
	('Tabasco','TC'),
	('Tamaulipas','TS'),
	('Tlaxcala','TL'),
	('Veracruz','VZ'),
	('Yucatán','YN'),
	('Zacatecas','ZS');